# Generated by Django 4.2.16 on 2026-01-05 02:11

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constellation",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                (
                    "faction_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "wormhole_class_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EveSDE",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "build_number",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "release_Date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "permissions": (("admin_access", "Can access admin page."),),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_de", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
                ("description_it_it", models.TextField(null=True)),
                ("description_ja", models.TextField(null=True)),
                ("description_ko_kr", models.TextField(null=True)),
                ("description_fr_fr", models.TextField(null=True)),
                ("description_nl_nl", models.TextField(null=True)),
                ("description_pl_pl", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_uk", models.TextField(null=True)),
                ("description_zh_hans", models.TextField(null=True)),
                (
                    "faction_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "nebular_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "wormhole_class_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SolarSystem",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                ("border", models.BooleanField(blank=True, default=False, null=True)),
                ("corridor", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "faction_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("fringe", models.BooleanField(blank=True, default=False, null=True)),
                ("hub", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "international",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("luminosity", models.FloatField(blank=True, default=None, null=True)),
                ("radius", models.FloatField(blank=True, default=None, null=True)),
                ("regional", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "security_class",
                    models.CharField(default=None, max_length=5, null=True),
                ),
                (
                    "security_status",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("star_id_raw", models.IntegerField(default=None, null=True)),
                (
                    "visual_effect",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "wormhole_class_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("x_2d", models.FloatField(blank=True, default=None, null=True)),
                ("y_2d", models.FloatField(blank=True, default=None, null=True)),
                (
                    "constellation",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.constellation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Stargate",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                ("item_type_id_raw", models.IntegerField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "solar_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                ("celestial_index", models.IntegerField()),
                ("item_type_id_raw", models.IntegerField()),
                ("orbit_id_raw", models.IntegerField()),
                ("orbit_index", models.IntegerField()),
                ("radius", models.IntegerField()),
                (
                    "solar_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planet",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Moon",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                ("celestial_index", models.IntegerField()),
                ("item_type_id_raw", models.IntegerField()),
                ("orbit_id_raw", models.IntegerField()),
                ("orbit_index", models.IntegerField()),
                ("radius", models.IntegerField()),
                (
                    "planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eve_sde.planet"
                    ),
                ),
                (
                    "solar_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moon",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="constellation",
            name="region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eve_sde.region",
            ),
        ),
    ]
