# Generated by Django 4.2.28 on 2026-02-24 23:24

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0011_alter_moon_planet_alter_moon_solar_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constellation",
            name="region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eve_sde.region",
            ),
        ),
    ]
