# Generated by Django 4.2.16 on 2026-03-01 01:40

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogmaEffect",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "display_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "disallow_auto_repeat",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "discharge_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "duration_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "effect_category_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "electronic_chance",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "guid",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "is_assistance",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "is_offensive",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "is_warp_safe",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "propulsion_chance",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("published", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "range_chance",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "distribution",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "falloff_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "range_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tracking_speed_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("icon_id", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "npc_usage_chance_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "npc_activation_chance_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "fitting_usage_chance_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "resistance_attribute_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TypeEffect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "dogma_effect",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.dogmaeffect",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effect",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
