# Generated by Django 4.2.16 on 2026-03-01 01:52

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0013_dogmaeffect_typeeffect"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_de",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_en",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_es",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_fr_fr",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_it_it",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_ja",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_ko_kr",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_nl_nl",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_pl_pl",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_ru",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_uk",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="description_zh_hans",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_de",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_en",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_es",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_fr_fr",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_it_it",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_ja",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_ko_kr",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_nl_nl",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_pl_pl",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_ru",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_uk",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dogmaeffect",
            name="display_name_zh_hans",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
