# Generated by Django 4.2.28 on 2026-03-02 00:10

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0014_dogmaeffect_description_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="packaged_volume",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
