# Generated by Django 4.2.28 on 2026-03-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0015_itemtype_packaged_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCStation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_de', models.CharField(max_length=250, null=True)),
                ('name_es', models.CharField(max_length=250, null=True)),
                ('name_it_it', models.CharField(max_length=250, null=True)),
                ('name_ja', models.CharField(max_length=250, null=True)),
                ('name_ko_kr', models.CharField(max_length=250, null=True)),
                ('name_fr_fr', models.CharField(max_length=250, null=True)),
                ('name_nl_nl', models.CharField(max_length=250, null=True)),
                ('name_pl_pl', models.CharField(max_length=250, null=True)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uk', models.CharField(max_length=250, null=True)),
                ('name_zh_hans', models.CharField(max_length=250, null=True)),
                ('x', models.FloatField(blank=True, default=None, null=True)),
                ('y', models.FloatField(blank=True, default=None, null=True)),
                ('z', models.FloatField(blank=True, default=None, null=True)),
                ('celestial_index', models.IntegerField(blank=True, default=None, null=True)),
                ('operation_id_raw', models.IntegerField(blank=True, default=None, null=True)),
                ('orbit_id_raw', models.IntegerField(blank=True, default=None, null=True)),
                ('orbit_index', models.IntegerField(blank=True, default=None, null=True)),
                ('owner_id_raw', models.IntegerField(blank=True, default=None, null=True)),
                ('reprocessing_efficiency', models.FloatField(blank=True, default=None, null=True)),
                ('reprocessing_hangar_flag', models.IntegerField(blank=True, default=None, null=True)),
                ('reprocessing_stations_take', models.FloatField(blank=True, default=None, null=True)),
                ('use_operation_name', models.BooleanField(blank=True, default=None, null=True)),
                ('item_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.itemtype')),
                ('solar_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.solarsystem')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ItemMarketGroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_de', models.CharField(max_length=250, null=True)),
                ('name_es', models.CharField(max_length=250, null=True)),
                ('name_it_it', models.CharField(max_length=250, null=True)),
                ('name_ja', models.CharField(max_length=250, null=True)),
                ('name_ko_kr', models.CharField(max_length=250, null=True)),
                ('name_fr_fr', models.CharField(max_length=250, null=True)),
                ('name_nl_nl', models.CharField(max_length=250, null=True)),
                ('name_pl_pl', models.CharField(max_length=250, null=True)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uk', models.CharField(max_length=250, null=True)),
                ('name_zh_hans', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('description_en', models.TextField(blank=True, default=None, null=True)),
                ('description_de', models.TextField(blank=True, default=None, null=True)),
                ('description_es', models.TextField(blank=True, default=None, null=True)),
                ('description_it_it', models.TextField(blank=True, default=None, null=True)),
                ('description_ja', models.TextField(blank=True, default=None, null=True)),
                ('description_ko_kr', models.TextField(blank=True, default=None, null=True)),
                ('description_fr_fr', models.TextField(blank=True, default=None, null=True)),
                ('description_nl_nl', models.TextField(blank=True, default=None, null=True)),
                ('description_pl_pl', models.TextField(blank=True, default=None, null=True)),
                ('description_ru', models.TextField(blank=True, default=None, null=True)),
                ('description_uk', models.TextField(blank=True, default=None, null=True)),
                ('description_zh_hans', models.TextField(blank=True, default=None, null=True)),
                ('has_types', models.BooleanField(default=False)),
                ('icon_id', models.IntegerField(blank=True, default=None, null=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemmarketgroup')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='itemtype',
            name='market_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eve_sde.itemmarketgroup'),
        ),
    ]
