# Generated by Django 4.2.28 on 2026-03-02 10:37

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0016_npcstation_itemmarketgroup_itemtype_market_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='market_group_id_raw',
        ),
    ]
