# Generated by Django 4.2.28 on 2026-03-02 13:48

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0017_remove_itemtype_market_group_id_raw"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintActivity",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("manufacturing", "Manufacturing"),
                            ("research_time", "Researching Time Efficiency"),
                            ("research_material", "Researching Material Efficiency"),
                            ("copying", "Copying"),
                            ("invention", "Invention"),
                            ("reaction", "Reaction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "max_production_limit",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "blueprint_item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_activities",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BlueprintActivityProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=None, null=True)),
                ("probability", models.FloatField(blank=True, default=None, null=True)),
                (
                    "blueprint_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="eve_sde.blueprintactivity",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BlueprintActivityMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "blueprint_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="eve_sde.blueprintactivity",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
